https://www.kaggle.com/hypnobear/absenteeism-at-work-dataset

https://www.kaggle.com/chetnasureka/absenteeismatwork/kernels

https://www.kaggle.com/shreytiwari/name-na

https://www.kaggle.com/miner16078/zenith-classification-and-clustering

https://www.kaggle.com/tejprash/theaggregatr-assign6

https://www.kaggle.com/kerneler/starter-absenteeism-at-work-7c360987-f

https://www.kaggle.com/dweepa/outliers-assign6


# Prepare Your Data For Machine Learning
Many machine learning algorithms make assumptions about your data. It is often a very good
idea to prepare your data in such a way to best expose the structure of the problem to the
machine learning algorithms that you intend to use. In this chapter you will discover how to
prepare your data for machine learning in Python using scikit-learn. After completing this
lesson you will know how to:
1. Rescale data.
2. Standardize data.
3. Normalize data.
4. Binarize data. 


## Need For Data Pre-processing
You almost always need to pre-process your data. It is a required step. A dificulty is that
diferent algorithms make diferent assumptions about your data and may require diferent
transforms. Further, when you follow all of the rules and prepare your data, sometimes algorithms
can deliver better results without pre-processing.
Generally, I would recommend creating many diferent views and transforms of your data,
then exercise a handful of algorithms on each view of your dataset. This will help you to 
ush
out which data transforms might be better at exposing the structure of your problem in general.

## Data Transforms


In this lesson you will work through 4 dierent data pre-processing recipes for machine learning.
The Pima Indian diabetes dataset is used in each recipe. Each recipe follows the same structure:
- Load the dataset.

- Split the dataset into the input and output variables for machine learning.
- Apply a pre-processing transform to the input variables.
- Summarize the data to show the change.


The scikit-learn library provides two standard idioms for transforming data. Each are useful
in diferent circumstances. The transforms are calculated in such a way that they can be applied
to your training data and any samples of data you may have in the future. The scikit-learn
documentation has some information on how to use various diferent pre-processing methods:

- Fit and Multiple Transform.
- Combined Fit-And-Transform.

The Fit and Multiple Transform method is the preferred approach. You call the fit()
function to prepare the parameters of the transform once on your data. Then later you can use
the transform() function on the same data to prepare it for modeling and again on the test or
validation dataset or new data that you may see in the future. The Combined Fit-And-Transform
is a convenience that you can use for one o tasks. This might be useful if you are interested
in plotting or summarizing the transformed data. You can review the preprocess API in
scikit-learn here1.


## Rescale Data
When your data is comprised of attributes with varying scales, many machine learning algorithms
can benefit from rescaling the attributes to all have the same scale. Often this is referred to
as normalization and attributes are often rescaled into the range between 0 and 1. This is
useful for optimization algorithms used in the core of machine learning algorithms like gradient
descent. It is also useful for algorithms that weight inputs like regression and neural networks
and algorithms that use distance measures like k-Nearest Neighbors. You can rescale your data
using scikit-learn using the MinMaxScaler class2.

In [1]:
# Rescale data (between 0 and 1)
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [2]:
data = pd.read_csv('Absenteeism_at_work.csv')

In [3]:
data.head(20)

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0   11                  26                 7                3        1   
1   36                   0                 7                3        1   
2    3                  23                 7                4        1   
3    7                   7                 7                5        1   
4   11                  23                 7                5        1   
5    3                  23                 7                6        1   
6   10                  22                 7                6        1   
7   20                  23                 7                6        1   
8   14                  19                 7                2        1   
9    1                  22                 7                2        1   
10  20                   1                 7                2        1   
11  20                   1                 7                3        1   
12  20                  11                 7                4        1   
13   3                  11                 7                4        1   
14   3                  23                 7                4        1   
15  24                  14                 7                6        1   
16   3                  23                 7                6        1   
17   3                  21                 7                2        1   
18   6                  11                 7                5        1   
19  33                  23                 8                4        1   

    Transportation expense  Distance from Residence to Work  Service time  \
0                      289                               36            13   
1                      118                               13            18   
2                      179                               51            18   
3                      279                                5            14   
4                      289                               36            13   
5                      179                               51            18   
6                      361                               52             3   
7                      260                               50            11   
8                      155                               12            14   
9                      235                               11            14   
10                     260                               50            11   
11                     260                               50            11   
12                     260                               50            11   
13                     179                               51            18   
14                     179                               51            18   
15                     246                               25            16   
16                     179                               51            18   
17                     179                               51            18   
18                     189                               29            13   
19                     248                               25            14   

    Age  Work load Average/day   Hit target  Disciplinary failure  Education  \
0    33                 239.554          97                     0          1   
1    50                 239.554          97                     1          1   
2    38                 239.554          97                     0          1   
3    39                 239.554          97                     0          1   
4    33                 239.554          97                     0          1   
5    38                 239.554          97                     0          1   
6    28                 239.554          97                     0          1   
7    36                 239.554          97                     0          1   
8    34                 239.554          97                     0          1   
9    37                 239.554

In [4]:
print(data.shape)

(740, 15)


In [10]:
array = data.values
array

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [11]:
array.shape

(740, 15)

In [18]:
# separate array into input and output components
X = array[:,0:15]
X

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [19]:
X.shape

(740, 15)

In [24]:
Y = array[:,14]
Y.shape

(740,)

In [29]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaler

MinMaxScaler(copy=True, feature_range=(0, 1))

In [30]:
rescaledX = scaler.fit_transform(X)
rescaledX

array([[0.286, 0.929, 0.583, ..., 0.   , 0.579, 0.033],
       [1.   , 0.   , 0.583, ..., 0.   , 0.632, 0.   ],
       [0.057, 0.821, 0.583, ..., 0.   , 0.632, 0.017],
       ...,
       [0.086, 0.   , 0.   , ..., 0.   , 0.789, 0.   ],
       [0.2  , 0.   , 0.   , ..., 0.   , 0.842, 0.   ],
       [0.971, 0.   , 0.   , ..., 0.   , 0.316, 0.   ]])

In [31]:
# summarize transformed data
set_printoptions(precision=3)

In [32]:
print(rescaledX[0:5,:])

[[0.286 0.929 0.583 0.25  0.    0.633 0.66  0.429 0.194 0.194 0.842 0.
  0.    0.579 0.033]
 [1.    0.    0.583 0.25  0.    0.    0.17  0.607 0.742 0.194 0.842 1.
  0.    0.632 0.   ]
 [0.057 0.821 0.583 0.5   0.    0.226 0.979 0.607 0.355 0.194 0.842 0.
  0.    0.632 0.017]
 [0.171 0.25  0.583 0.75  0.    0.596 0.    0.464 0.387 0.194 0.842 0.
  0.    0.263 0.033]
 [0.286 0.821 0.583 0.75  0.    0.633 0.66  0.429 0.194 0.194 0.842 0.
  0.    0.579 0.017]]


In [33]:
rescaledX.shape

(740, 15)

## Standardize Data

Standardization is a useful technique to transform attributes with a Gaussian distribution and
differing means and standard deviations to a standard Gaussian distribution with a mean of
0 and a standard deviation of 1. It is most suitable for techniques that assume a Gaussian
distribution in the input variables and work better with rescaled data, such as linear regression,
logistic regression and linear discriminate analysis. You can standardize data using scikit-learn
with the StandardScaler class3.

In [34]:
# Standardize data (0 mean, 1 stdev)
from sklearn.preprocessing import StandardScaler
from numpy import set_printoptions

In [35]:
array_std_data = data.values
array_std_data

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [36]:
array_std_data.shape

(740, 15)

In [45]:
# separate array into input and output components
X_ = array[:,0:15]
X_

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [49]:
X_.shape

(740, 15)

In [46]:
Y_ = array[:,14]
Y_

array([  4.,   0.,   2.,   4.,   2.,   2.,   8.,   4.,  40.,   8.,   8.,
         8.,   8.,   1.,   4.,   8.,   2.,   8.,   8.,   2.,   8.,   1.,
        40.,   4.,   8.,   7.,   1.,   4.,   8.,   2.,   8.,   8.,   4.,
         8.,   2.,   1.,   8.,   4.,   8.,   4.,   2.,   4.,   4.,   8.,
         2.,   3.,   3.,   4.,   8.,  32.,   0.,   0.,   2.,   2.,   0.,
         0.,   3.,   3.,   0.,   1.,   3.,   4.,   3.,   3.,   0.,   1.,
         3.,   3.,   3.,   2.,   2.,   5.,   8.,   3.,  16.,   8.,   2.,
         8.,   1.,   3.,   1.,   1.,   8.,   8.,   5.,  32.,   8.,  40.,
         1.,   8.,   3.,   8.,   3.,   4.,   1.,   3.,  24.,   3.,   1.,
        64.,   2.,   8.,   2.,   8.,  56.,   8.,   3.,   3.,   2.,   8.,
         2.,   8.,   2.,   1.,   1.,   1.,   8.,   2.,   2.,   2.,   1.,
         2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   8.,   8.,   2.,
         2.,   2.,   0.,   1.,   3.,   1.,   8.,   8.,   2.,   8.,   2.,
         8.,   8.,   8.,   2.,   2.,   1.,   8.,   

In [47]:
Y_.shape

(740,)

In [50]:
scaler = StandardScaler().fit(X_)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [51]:
rescaledX_ = scaler.transform(X_)
rescaledX_

array([[-0.637,  0.805,  0.197, ..., -0.434,  0.776, -0.22 ],
       [ 1.633, -2.28 ,  0.197, ..., -0.434,  1.009, -0.52 ],
       [-1.364,  0.449,  0.197, ..., -0.434,  1.009, -0.37 ],
       ...,
       [-1.273, -2.28 , -1.842, ..., -0.434,  1.71 , -0.52 ],
       [-0.91 , -2.28 , -1.842, ..., -0.434,  1.943, -0.52 ],
       [ 1.542, -2.28 , -1.842, ..., -0.434, -0.392, -0.52 ]])

In [52]:
# summarize transformed data
set_printoptions(precision=3)

In [53]:
print(rescaledX_[0:5,:])

[[-0.637  0.805  0.197 -0.644 -1.39   1.011  0.43   0.102 -0.533 -0.818
   0.639 -0.239 -0.434  0.776 -0.22 ]
 [ 1.633 -2.28   0.197 -0.644 -1.39  -1.544 -1.122  1.243  2.093 -0.818
   0.639  4.183 -0.434  1.009 -0.52 ]
 [-1.364  0.449  0.197  0.06  -1.39  -0.633  1.441  1.243  0.239 -0.818
   0.639 -0.239 -0.434  1.009 -0.37 ]
 [-1.    -1.45   0.197  0.764 -1.39   0.862 -1.661  0.33   0.394 -0.818
   0.639 -0.239 -0.434 -0.625 -0.22 ]
 [-0.637  0.449  0.197  0.764 -1.39   1.011  0.43   0.102 -0.533 -0.818
   0.639 -0.239 -0.434  0.776 -0.37 ]]


## Normalize Data
Normalizing in scikit-learn refers to rescaling each observation (row) to have a length of 1 (called
a unit norm or a vector with the length of 1 in linear algebra). This pre-processing method
can be useful for sparse datasets (lots of zeros) with attributes of varying scales when using
algorithms that weight input values such as neural networks and algorithms that use distance
measures such as k-Nearest Neighbors. You can normalize data in Python with scikit-learn
using the Normalizer class4.

In [54]:
# Normalize data (length of 1)
from sklearn.preprocessing import Normalizer
from numpy import set_printoptions

In [56]:
array_nor_data = data.values
array_nor_data

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [58]:
array_nor_data.shape

(740, 15)

In [60]:
# separ.shapeate array into input and output components
X_nor = array[:,0:15]
X_nor

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [61]:
X_nor.shape

(740, 15)

In [63]:
Y_nor = array[:,14]
Y_nor

array([  4.,   0.,   2.,   4.,   2.,   2.,   8.,   4.,  40.,   8.,   8.,
         8.,   8.,   1.,   4.,   8.,   2.,   8.,   8.,   2.,   8.,   1.,
        40.,   4.,   8.,   7.,   1.,   4.,   8.,   2.,   8.,   8.,   4.,
         8.,   2.,   1.,   8.,   4.,   8.,   4.,   2.,   4.,   4.,   8.,
         2.,   3.,   3.,   4.,   8.,  32.,   0.,   0.,   2.,   2.,   0.,
         0.,   3.,   3.,   0.,   1.,   3.,   4.,   3.,   3.,   0.,   1.,
         3.,   3.,   3.,   2.,   2.,   5.,   8.,   3.,  16.,   8.,   2.,
         8.,   1.,   3.,   1.,   1.,   8.,   8.,   5.,  32.,   8.,  40.,
         1.,   8.,   3.,   8.,   3.,   4.,   1.,   3.,  24.,   3.,   1.,
        64.,   2.,   8.,   2.,   8.,  56.,   8.,   3.,   3.,   2.,   8.,
         2.,   8.,   2.,   1.,   1.,   1.,   8.,   2.,   2.,   2.,   1.,
         2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   8.,   8.,   2.,
         2.,   2.,   0.,   1.,   3.,   1.,   8.,   8.,   2.,   8.,   2.,
         8.,   8.,   8.,   2.,   2.,   1.,   8.,   

In [64]:
Y_nor.shape

(740,)

In [66]:
scaler_nor_data = Normalizer().fit(X_nor)
scaler_nor_data

Normalizer(copy=True, norm='l2')

In [67]:
normalizedX = scaler.transform(X_nor)
normalizedX

array([[0.028, 0.066, 0.018, ..., 0.003, 0.076, 0.01 ],
       [0.123, 0.   , 0.024, ..., 0.003, 0.106, 0.   ],
       [0.009, 0.071, 0.022, ..., 0.003, 0.096, 0.006],
       ...,
       [0.013, 0.   , 0.   , ..., 0.003, 0.108, 0.   ],
       [0.021, 0.   , 0.   , ..., 0.003, 0.093, 0.   ],
       [0.1  , 0.   , 0.   , ..., 0.003, 0.072, 0.   ]])

In [68]:
# summarize transformed data
set_printoptions(precision=3)
print(normalizedX[0:5,:])

[[0.028 0.066 0.018 0.008 0.003 0.735 0.092 0.033 0.084 0.609 0.247 0.
  0.003 0.076 0.01 ]
 [0.123 0.    0.024 0.01  0.003 0.402 0.044 0.061 0.17  0.817 0.331 0.003
  0.003 0.106 0.   ]
 [0.009 0.071 0.022 0.012 0.003 0.553 0.158 0.056 0.117 0.74  0.3   0.
  0.003 0.096 0.006]
 [0.018 0.018 0.018 0.013 0.003 0.727 0.013 0.036 0.102 0.624 0.253 0.
  0.003 0.063 0.01 ]
 [0.028 0.059 0.018 0.013 0.003 0.735 0.092 0.033 0.084 0.609 0.247 0.
  0.003 0.076 0.005]]


## Binarize Data (Make Binary)
You can transform your data using a binary threshold. All values above the threshold are
marked 1 and all equal to or below are marked as 0. This is called binarizing your data or
thresholding your data. It can be useful when you have probabilities that you want to make
into crisp values. It is also useful when feature engineering and you want to add new features
that indicate something meaningful. You can create new binary attributes in Python using
scikit-learn with the Binarizer class5.

In [70]:
# binarization
from sklearn.preprocessing import Binarizer
from numpy import set_printoptions

In [71]:
array_bin = data.values
array_bin

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [72]:
array_bin.shape

(740, 15)

In [82]:
# separate array into input and output components
X_bin = array[:,0:15]
X_bin         

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [83]:
Y_bin = array[:,14]
Y_bin

array([  4.,   0.,   2.,   4.,   2.,   2.,   8.,   4.,  40.,   8.,   8.,
         8.,   8.,   1.,   4.,   8.,   2.,   8.,   8.,   2.,   8.,   1.,
        40.,   4.,   8.,   7.,   1.,   4.,   8.,   2.,   8.,   8.,   4.,
         8.,   2.,   1.,   8.,   4.,   8.,   4.,   2.,   4.,   4.,   8.,
         2.,   3.,   3.,   4.,   8.,  32.,   0.,   0.,   2.,   2.,   0.,
         0.,   3.,   3.,   0.,   1.,   3.,   4.,   3.,   3.,   0.,   1.,
         3.,   3.,   3.,   2.,   2.,   5.,   8.,   3.,  16.,   8.,   2.,
         8.,   1.,   3.,   1.,   1.,   8.,   8.,   5.,  32.,   8.,  40.,
         1.,   8.,   3.,   8.,   3.,   4.,   1.,   3.,  24.,   3.,   1.,
        64.,   2.,   8.,   2.,   8.,  56.,   8.,   3.,   3.,   2.,   8.,
         2.,   8.,   2.,   1.,   1.,   1.,   8.,   2.,   2.,   2.,   1.,
         2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   8.,   8.,   2.,
         2.,   2.,   0.,   1.,   3.,   1.,   8.,   8.,   2.,   8.,   2.,
         8.,   8.,   8.,   2.,   2.,   1.,   8.,   

In [84]:
Y_bin.shape

(740,)

In [85]:
binarizer = Binarizer(threshold=0.0).fit(X_bin)
binarizer

Binarizer(copy=True, threshold=0.0)

In [86]:
binaryX = binarizer.transform(X_bin)
binaryX

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [87]:
binaryX.shape

(740, 15)

In [88]:
# summarize transformed data
set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]]


# Feature Selection For Machine Learning
The data features that you use to train your machine learning models have a huge influence on
the performance you can achieve. Irrelevant or partially relevant features can negatively impact
model performance. In this chapter you will discover automatic feature selection techniques
that you can use to prepare your machine learning data in Python with scikit-learn. After
completing this lesson you will know how to use:

1. Univariate Selection.
2. Recursive Feature Elimination.
3. Principle Component Analysis.
4. Feature Importance.


## Feature Selection

Feature selection is a process where you automatically select those features in your data that
contribute most to the prediction variable or output in which you are interested. Having
irrelevant features in your data can decrease the accuracy of many models, especially linear
algorithms like linear and logistic regression. Three benets of performing feature selection
before modeling your data are:

- Reduces Overfitting: Less redundant data means less opportunity to make decisions based on noise.
- Improves Accuracy: Less misleading data means modeling accuracy improves.
- Reduces Training Time: Less data means that algorithms train faster.

You can learn more about feature selection with scikit-learn in the article Feature selection1.
Each feature selection recipes will use the Pima Indians onset of diabetes dataset.

# Univariate Selection

Statistical tests can be used to select those features that have the strongest relationship with
the output variable. The scikit-learn library provides the SelectKBest class2 that can be used
with a suite of diferent statistical tests to select a specific number of features. The example
below uses the Chi-Squared (f2) statistical test for non-negative features to select 4 of the best
features from the Pima Indians onset of diabetes dataset.

In [89]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [91]:
# load data
array_univ_selec = data.values
array_univ_selec

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [92]:
array_univ_selec.shape

(740, 15)

In [94]:
X_univ = array_univ_selec[:,0:15]
X_univ

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [96]:
Y_univ = array_univ_selec[:,14]
Y_univ

array([  4.,   0.,   2.,   4.,   2.,   2.,   8.,   4.,  40.,   8.,   8.,
         8.,   8.,   1.,   4.,   8.,   2.,   8.,   8.,   2.,   8.,   1.,
        40.,   4.,   8.,   7.,   1.,   4.,   8.,   2.,   8.,   8.,   4.,
         8.,   2.,   1.,   8.,   4.,   8.,   4.,   2.,   4.,   4.,   8.,
         2.,   3.,   3.,   4.,   8.,  32.,   0.,   0.,   2.,   2.,   0.,
         0.,   3.,   3.,   0.,   1.,   3.,   4.,   3.,   3.,   0.,   1.,
         3.,   3.,   3.,   2.,   2.,   5.,   8.,   3.,  16.,   8.,   2.,
         8.,   1.,   3.,   1.,   1.,   8.,   8.,   5.,  32.,   8.,  40.,
         1.,   8.,   3.,   8.,   3.,   4.,   1.,   3.,  24.,   3.,   1.,
        64.,   2.,   8.,   2.,   8.,  56.,   8.,   3.,   3.,   2.,   8.,
         2.,   8.,   2.,   1.,   1.,   1.,   8.,   2.,   2.,   2.,   1.,
         2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   8.,   8.,   2.,
         2.,   2.,   0.,   1.,   3.,   1.,   8.,   8.,   2.,   8.,   2.,
         8.,   8.,   8.,   2.,   2.,   1.,   8.,   

In [97]:
Y_univ.shape

(740,)

In [104]:
# feature extraction
test = SelectKBest(score_func=chi2, k=15)
test

SelectKBest(k=15, score_func=<function chi2 at 0x7fae9f39c488>)

In [105]:
fit = test.fit(X_univ, Y_univ)
fit

SelectKBest(k=15, score_func=<function chi2 at 0x7fae9f39c488>)

In [106]:
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)

[1.933e+02 1.316e+03 7.598e+01 1.710e+01 2.178e+01 1.684e+03 2.242e+02
 3.408e+01 3.606e+01 2.522e+02 5.757e+00 6.327e+02 6.053e+00 1.711e+01
 1.897e+04]


In [107]:
features = fit.transform(X_univ)
# summarize selected features
print(features[0:5,:])

[[ 11.     26.      7.      3.      1.    289.     36.     13.     33.
  239.554  97.      0.      1.     30.      4.   ]
 [ 36.      0.      7.      3.      1.    118.     13.     18.     50.
  239.554  97.      1.      1.     31.      0.   ]
 [  3.     23.      7.      4.      1.    179.     51.     18.     38.
  239.554  97.      0.      1.     31.      2.   ]
 [  7.      7.      7.      5.      1.    279.      5.     14.     39.
  239.554  97.      0.      1.     24.      4.   ]
 [ 11.     23.      7.      5.      1.    289.     36.     13.     33.
  239.554  97.      0.      1.     30.      2.   ]]


In [108]:
features.shape

(740, 15)

### Recursive Feature Elimination
The Recursive Feature Elimination (or RFE) works by recursively removing attributes and
building a model on those attributes that remain. It uses the model accuracy to identify which

## Principal Component Analysis
Principal Component Analysis (or PCA) uses linear algebra to transform the dataset into a
compressed form. Generally this is called a data reduction technique. A property of PCA is that
you can choose the number of dimensions or principal components in the transformed result. In
the example below, we use PCA and select 3 principal components. Learn more about the PCA
class in scikit-learn by reviewing the API4.

In [109]:
from sklearn.decomposition import PCA

In [110]:
array_pca = data.values

In [112]:
X_pca = array_pca[:,0:15]
X_pca

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [113]:
X_pca.shape

(740, 15)

In [115]:
Y_pca = array[:,14]
Y_pca

array([  4.,   0.,   2.,   4.,   2.,   2.,   8.,   4.,  40.,   8.,   8.,
         8.,   8.,   1.,   4.,   8.,   2.,   8.,   8.,   2.,   8.,   1.,
        40.,   4.,   8.,   7.,   1.,   4.,   8.,   2.,   8.,   8.,   4.,
         8.,   2.,   1.,   8.,   4.,   8.,   4.,   2.,   4.,   4.,   8.,
         2.,   3.,   3.,   4.,   8.,  32.,   0.,   0.,   2.,   2.,   0.,
         0.,   3.,   3.,   0.,   1.,   3.,   4.,   3.,   3.,   0.,   1.,
         3.,   3.,   3.,   2.,   2.,   5.,   8.,   3.,  16.,   8.,   2.,
         8.,   1.,   3.,   1.,   1.,   8.,   8.,   5.,  32.,   8.,  40.,
         1.,   8.,   3.,   8.,   3.,   4.,   1.,   3.,  24.,   3.,   1.,
        64.,   2.,   8.,   2.,   8.,  56.,   8.,   3.,   3.,   2.,   8.,
         2.,   8.,   2.,   1.,   1.,   1.,   8.,   2.,   2.,   2.,   1.,
         2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   8.,   8.,   2.,
         2.,   2.,   0.,   1.,   3.,   1.,   8.,   8.,   2.,   8.,   2.,
         8.,   8.,   8.,   2.,   2.,   1.,   8.,   

In [116]:
Y_pca.shape

(740,)

In [127]:
# feature extraction
pca = PCA(n_components=3)
pca

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [128]:
fit = pca.fit(X_pca)
fit

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [129]:
# summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

Explained Variance: [0.673 0.228 0.037]
[[-3.853e-02 -1.486e-02  7.006e-03  7.375e-04  5.966e-04  9.967e-01
   6.109e-02 -2.268e-02 -2.234e-02  3.733e-03 -4.534e-03  3.654e-04
  -5.730e-04 -8.596e-03  5.488e-03]
 [ 3.041e-02 -2.848e-02 -1.494e-02  4.840e-04  4.317e-03 -1.204e-03
  -3.298e-02 -6.058e-04 -6.215e-03  9.983e-01 -8.619e-03  1.861e-04
  -1.220e-03 -1.055e-02  1.024e-02]
 [ 4.399e-01 -1.510e-01  1.647e-02 -9.818e-03  5.779e-03  6.322e-02
  -8.398e-01 -8.429e-02  3.281e-02 -4.817e-02  9.506e-04  1.293e-03
   8.099e-03 -6.649e-02  2.429e-01]]


## Feature Importance
Bagged decision trees like Random Forest and Extra Trees can be used to estimate the importance
of features. In the example below we construct a ExtraTreesClassifier classier for the Pima
Indians onset of diabetes dataset. You can learn more about the ExtraTreesClassifier class5
in the scikit-learn API.

In [130]:
# Feature Importance with Extra Trees Classifier

from sklearn.ensemble import ExtraTreesClassifier

In [131]:
array_feture_impor = data.values
array_feture_impor

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [132]:
array_feture_impor.shape

(740, 15)

In [135]:
X_feature = array_feture_impor[:,0:15]
X_feature

array([[11., 26.,  7., ...,  1., 30.,  4.],
       [36.,  0.,  7., ...,  1., 31.,  0.],
       [ 3., 23.,  7., ...,  1., 31.,  2.],
       ...,
       [ 4.,  0.,  0., ...,  1., 34.,  0.],
       [ 8.,  0.,  0., ...,  1., 35.,  0.],
       [35.,  0.,  0., ...,  1., 25.,  0.]])

In [136]:
X_feature.shape

(740, 15)

In [138]:
Y_feature = array_feture_impor[:,14]
Y_feature

array([  4.,   0.,   2.,   4.,   2.,   2.,   8.,   4.,  40.,   8.,   8.,
         8.,   8.,   1.,   4.,   8.,   2.,   8.,   8.,   2.,   8.,   1.,
        40.,   4.,   8.,   7.,   1.,   4.,   8.,   2.,   8.,   8.,   4.,
         8.,   2.,   1.,   8.,   4.,   8.,   4.,   2.,   4.,   4.,   8.,
         2.,   3.,   3.,   4.,   8.,  32.,   0.,   0.,   2.,   2.,   0.,
         0.,   3.,   3.,   0.,   1.,   3.,   4.,   3.,   3.,   0.,   1.,
         3.,   3.,   3.,   2.,   2.,   5.,   8.,   3.,  16.,   8.,   2.,
         8.,   1.,   3.,   1.,   1.,   8.,   8.,   5.,  32.,   8.,  40.,
         1.,   8.,   3.,   8.,   3.,   4.,   1.,   3.,  24.,   3.,   1.,
        64.,   2.,   8.,   2.,   8.,  56.,   8.,   3.,   3.,   2.,   8.,
         2.,   8.,   2.,   1.,   1.,   1.,   8.,   2.,   2.,   2.,   1.,
         2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   8.,   8.,   2.,
         2.,   2.,   0.,   1.,   3.,   1.,   8.,   8.,   2.,   8.,   2.,
         8.,   8.,   8.,   2.,   2.,   1.,   8.,   

In [139]:
Y_feature.shape

(740,)

In [141]:
# feature extraction
model = ExtraTreesClassifier()
model

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [142]:
model.fit(X_feature, Y_feature)
print(model.feature_importances_)

[0.035 0.105 0.059 0.061 0.037 0.035 0.022 0.021 0.025 0.064 0.052 0.053
 0.01  0.025 0.397]


/home/felipemartinezs/.local/lib/python3.5/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


You can see that we are given an importance score for each attribute where the larger the
score, the more important the attribute. The scores highlight the importance of plas, age and
mass.